language: java
jdk:
  - oraclejdk8
services:
  - mysql
dist: trusty
sudo: required
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
before_script:
  - mysql -u root -e 'create database stockmarket;'
  - mysql -u root -e 'create user makler;'
  - mysql -u root -e 'grant all on stockmarket.* to 'makler'@'localhost' identified by 'makler';'
