language: java
jdk:
  - oraclejdk8
services:
  - mysql
dist: trusty
sudo: required
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
before_script:
  - sudo mysql -h localhost -u root -p -e 'CREATE DATABASE stockmarket;'
  - sudo mysql -h localhost -u root -p -e 'CREATE USER 'makler'@'localhost' IDENTIFIED BY 'makler';'
  - sudo mysql -h localhost -u root -p -e 'GRANT ALL ON stockmarket.* TO 'makler'@'localhost';'
