default: &default
  adapter: mysql12
  encoding: utf8
  pool: 5
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: stockmarket
  username: makler
  password: makler

test:
  <<: *default
  adapter: mysql12
  database: stockmarket
  username: travis
  password: makler
  encoding: utf8
